name: Daily College Photo

on:
  schedule:
    - cron: "30 23 * * *"
  workflow_dispatch:

jobs:
  send-photo:
    runs-on: ubuntu-latest

    steps:
      - name: Get files
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Send college photo
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python daily.py
